Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -52,30 +52,43 @@ jobs:
           name: Postman-Reports
           path: Gorest_Postman/testArtifacts
  
+
   jmeter-tests:
-   runs-on: ubuntu-latest
-   steps:
-    - name: Checkout Repository
-      uses: actions/checkout@v4
-    - name: Install Java
-      uses: actions/setup-java@v2
-      with:
-        java-version: '11'
-        distribution: 'adopt'
-    - name: Download and Install JMeter
-      run: |
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout Repository
+        uses: actions/checkout@v4
+      
+      - name: Install Java
+        uses: actions/setup-java@v2
+        with:
+          java-version: '11'
+          distribution: 'adopt'
+
+      - name: Download and Install JMeter
+        run: |
           wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.3.tgz
           tar -xf apache-jmeter-5.6.3.tgz
           sudo mv apache-jmeter-5.6.3 /opt/
           echo 'export PATH=/opt/apache-jmeter-5.6.3/bin:$PATH' >> ~/.bashrc
           source ~/.bashrc
-    - name: Run JMeter Tests
-      run: /opt/apache-jmeter-5.6.3/bin/jmeter -n -t "JmeterAssignment/Jmeter_Assignment.jmx"
-    - name: Upload Results
-      uses: actions/upload-artifact@v3
-      with:
+      
+      - name: Run JMeter Tests
+        run: |
+          /opt/apache-jmeter-5.6.3/bin/jmeter -n -t "JmeterAssignment/Jmeter_Assignment.jmx" -l jmeter-results.jtl || exit 0
+          if [ $? -eq 0 ]; then
+            echo "JMeter tests ran successfully."
+          else
+            echo "JMeter tests failed."
+            exit 1
+          fi
+
+      - name: Upload Results
+        uses: actions/upload-artifact@v3
+        with:
           name: jmeter-results
-          path: JmeterAssignment
+          path: jmeter-results.jtl
+
 
 
 
